INSERT INTO task_table (id, task_name, performer_id, description, status)
VALUES
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
     'Подготовить описание API',
     '11111111-1111-1111-1111-111111111111',
     'Подготовить и проверить описание REST API в OpenAPI.',
     'DONE'),
    ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
     'Реализовать пагинацию задач',
     '11111111-1111-1111-1111-111111111111',
     'Добавить получение списка задач с параметрами page, size и sort.',
     'IN_PROGRESS'),
    ('cccccccc-cccc-cccc-cccc-cccccccccccc',
     'Проверить интеграцию с Kafka',
     '22222222-2222-2222-2222-222222222222',
     'Проверить отправку событий сервиса в Kafka.',
     'HOLD'),
    ('dddddddd-dddd-dddd-dddd-dddddddddddd',
     'Добавить обработку ошибок',
     NULL,
     'Проверить единый формат ошибок и обработку 400/404.',
     'NEW'),
    ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
     'Подготовить Docker окружение',
     NULL,
     'Проверить запуск PostgreSQL, Kafka и приложения через Docker Compose.',
     'NEW');
